### ISSUE TITLE
a panic risk of function SeekPrefixWatch in file "iter.go"

### ISSUE THREAD

**Issue by xpineal** [hashicorp/go-immutable-radix#28] opened 2019-10-03 03:21 UTC
As following code, the variable "search" could be 0-length byte slice. But the last line of following code quote the "search[0]" directly.

```
		// Consume the search prefix
		if len(n.prefix) > len(search) {
			search = []byte{}
		} else {
			search = search[len(n.prefix):]
		}

		// Otherwise, take the lower bound next edge.
		idx, lbNode := n.getLowerBoundEdge(search[0])
```

**Comment by ncabatoff** [comment] 2019-10-03 14:07
I don't think `search` could be zero length slice at that point in the function, because we've already determined that it's an exact match for `n.prefix`, and moreover that n is an inner node.

**Comment by absolute8511** [comment] 2021-02-25 04:41
@ncabatoff Actually, it can be reproduced by insert and seek with following data

```
insert key with bytes [1, 0, 1, 0] and [1, 0, 1, 0, 1]
seeklowerbound with [1, 0, 1]
```

**Comment by banks** [comment] 2021-06-28 20:41
Fixed in https://github.com/hashicorp/go-immutable-radix/releases/tag/v1.3.1, thanks for reporting this!

**Closed** 2021-07-02 18:54 UTC
